#include "base/GraphUtils.hpp"
#include "utils/logging.hpp"

#include <nexusflow/Pipeline.hpp>
#include <nexusflow/PipelineBuilder.hpp>

#include <memory>
#include <string>
#include <unordered_set>
#include <utility>
#include <vector>

namespace nexusflow {

// --- PipelineBuilder's Private Implementation (m_pImpl) ---
// This class is now extremely simple. It's just a data-holding struct
// to store the user's configuration before the Graph is built.
class PipelineBuilder::Impl {
public:
    std::string pipelineName = "Programmatically_Built_Pipeline";
    std::vector<std::shared_ptr<Module>> modules;
    struct Connection {
        std::string srcModuleName;
        std::string srcPort;
        std::string dstModuleName;
        std::string dstPort;
    };

    std::vector<Connection> connections;
    PipelineConfig config = PipelineConfig::Default();  // Default configuration
};

// --- PipelineBuilder's Public Methods ---

PipelineBuilder::PipelineBuilder() : m_pImpl(std::make_unique<Impl>()) {}

PipelineBuilder::~PipelineBuilder() = default;

// --- Move Semantics ---
// The default move operations generated by the compiler are sufficient here.
PipelineBuilder::PipelineBuilder(PipelineBuilder&&) noexcept = default;
PipelineBuilder& PipelineBuilder::operator=(PipelineBuilder&&) noexcept = default;

PipelineBuilder& PipelineBuilder::AddModule(const std::shared_ptr<Module>& module) {
    if (m_pImpl && module) {
        m_pImpl->modules.push_back(module);
    }
    return *this;
}

PipelineBuilder& PipelineBuilder::WithName(const std::string& pipelineName) {
    if (m_pImpl && !pipelineName.empty()) {
        m_pImpl->pipelineName = pipelineName;
    }
    return *this;
}

PipelineBuilder& PipelineBuilder::Connect(const std::string& srcModuleName, const std::string& dstModuleName) {
    return Connect(srcModuleName, kDefaultOutputPort, dstModuleName, kDefaultInputPort);
}

PipelineBuilder& PipelineBuilder::Connect(const std::string& srcModuleName, const std::string& srcPort,
                                          const std::string& dstModuleName, const std::string& dstPort) {
    if (m_pImpl && !srcModuleName.empty() && !dstModuleName.empty()) {
        m_pImpl->connections.push_back(Impl::Connection{srcModuleName, srcPort, dstModuleName, dstPort});
    }
    return *this;
}

PipelineBuilder& PipelineBuilder::WithConfig(const PipelineConfig& config) {
    if (m_pImpl) {
        m_pImpl->config = config;
    }
    return *this;
}

std::unique_ptr<Pipeline> PipelineBuilder::Build() {
    if (!m_pImpl) {
        return nullptr; // Builder has been consumed
    }

    graphutils::GraphSpec spec;
    spec.graphName = m_pImpl->pipelineName;
    std::unordered_set<std::string> seenModuleNames;

    for (const auto& module_ptr : m_pImpl->modules) {
        if (!module_ptr) continue;

        const std::string& moduleName = module_ptr->GetModuleName();
        if (moduleName.empty()) {
            LOG_ERROR("PipelineBuilder: encountered a module with an empty name.");
            return nullptr;
        }
        if (!seenModuleNames.insert(moduleName).second) {
            LOG_ERROR("PipelineBuilder: duplicate module name '{}'.", moduleName);
            return nullptr;
        }

        spec.nodes.push_back(graphutils::GraphNodeSpec{moduleName, "", {}, module_ptr});
    }

    for (const auto& conn : m_pImpl->connections) {
        spec.connections.push_back(
            graphutils::GraphConnectionSpec{conn.srcModuleName, conn.srcPort, conn.dstModuleName, conn.dstPort});
    }

    auto graph = graphutils::CreateGraphFromSpec(spec);
    if (!graph) {
        return nullptr;
    }

    auto pipeline = std::unique_ptr<Pipeline>(new Pipeline());
    pipeline->InitWithGraph(std::move(graph), m_pImpl->config);

    m_pImpl.reset(); // Consume the builder

    return pipeline;
}

} // namespace nexusflow
