
message(STATUS "***************************** [Summary] *****************************")
message(STATUS "CPU Architecture                                       ")
message(STATUS "  CMAKE_HOST_SYSTEM_PROCESSOR                          : ${CMAKE_HOST_SYSTEM_PROCESSOR}")
message(STATUS "  CPU_TYPE                                             : ${CPU_TYPE}")
message(STATUS "Configure                                              ")
message(STATUS "  CMAKE_BUILD_TYPE                                     : ${CMAKE_BUILD_TYPE}")
message(STATUS "Project Info:")
message(STATUS "  Name                                                 : ${PROJECT_NAME}")
message(STATUS "  Meta                                                 : ${PROJECT_META}")
message(STATUS "  Version                                              : ${PROJECT_VERSION_MAJOR}.${PROJECT_VERSION_MINOR}.${PROJECT_VERSION_PATCH}")
message(STATUS "  Versioning                                           : semantic versioning (major.minor.patch)")
message(STATUS "Option:                                                ")
message(STATUS "  NF_WITH_TESTING                                       : ${NF_WITH_TESTING}")
message(STATUS "Install Dir                                            : ${CMAKE_INSTALL_PREFIX}")
message(STATUS "*********************************************************************")
